apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "sklearn-iris"
spec:
  predictor:
    model:
      modelFormat:
        name: mlflow
      storageUri: '{{ mlflow.blob["iris demo2"] }}'
